name: sreyastha_gps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter: 
    sdk: flutter
  geolocator: ^7.6.0
  flutter_map: ^0.14.0
  flutter_compass: ^0.7.0
  latlong2: ^0.8.0
  google_fonts: ^2.1.0
  expandable: ^5.0.1

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

