name: sreyastha_gps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter: 
    sdk: flutter
  geolocator: ^7.6.0
  flutter_map: ^0.14.0
  flutter_compass: ^0.7.0
  latlong2: ^0.8.0
  google_fonts: ^2.1.0
  expandable: ^5.0.1
  path_provider: ^2.0.6
  file_picker: ^4.1.6
  open_file: ^3.2.1
  csv: ^5.0.0
  permission_handler: ^8.2.5
  razorpay_flutter: ^1.2.7
  toast: ^0.1.5
  http: ^0.13.4
  shared_preferences: ^2.0.8

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/json_files/
